discord:
  token: ${DISCORD_BOT_TOKEN}
  client_id: ${DISCORD_CLIENT_ID}
  client_secret: ${DISCORD_CLIENT_SECRET}
  RoleID: ${DISCORD_ROLE_ID}
  redirect_url: ${RAILWAY_PUBLIC_DOMAIN}/oauth2/callback
  enabled: true
  command_prefix: "!"
  notification_channel_id: ${DISCORD_NOTIFICATION_CHANNEL}

server:
  port: "8080"

logging:
  log_level: "debug"

paths:
  commands_config: "configs/commands.yaml"

database:
  volumeMountPath: "/app/data2"
  name: "keeper.db"

gift_code:
  salt: "${GIFT_CODE_SALT}"
  min_length: 6
  max_length: 12
  api_endpoint: "https://wos-giftcode-api.centurygame.com/api"
  api_timeout: 30

scrape:
  sites:
    - name: "VG247"
      url: "https://www.vg247.com/whiteout-survival-codes"
      selector: "ul li strong"
    - name: "Lootbar"
      url: "https://lootbar.gg/blog/en/whiteout-survival-newest-codes.html"
      selector: ".code-block"
