discord:
  token: ${DISCORD_BOT_TOKEN}
  client_id: ${DISCORD_CLIENT_ID}
  client_secret: ${DISCORD_CLIENT_SECRET}
  redirect_url: ${RAILWAY_PUBLIC_DOMAIN}/oauth2/callback
  enabled: true

server:
  port: "8080"

logging:
  log_level: "debug"
