discord:
  token: ${DISCORD_BOT_TOKEN}
  client_id: ${DISCORD_CLIENT_ID}
  client_secret: ${DISCORD_CLIENT_SECRET}
  redirect_url: http://yourserver.com/oauth2/callback
  command_prefix: "!"
server:
  port: "8080"
logging:
  log_level: "debug"
